apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich-db
  namespace: cnpg-cluster
spec:
  cluster:
    name: cnpg-cluster
  extensions:
  - ensure: present
    name: pgvector
  name: immich
  owner: immich
status: {}
