apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-cluster
  namespace: cnpg-cluster
spec:
  affinity: {}
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.3-v0.2.1
  instances: 3
  managed:
    roles:
    - login: true
      name: immich
      passwordSecret:
        name: immich
  postgresql:
    syncReplicaElectionConstraint:
      enabled: false
  resources: {}
  storage:
    pvcTemplate:
      resources: {}
      storageClassName: local-path
    resizeInUseVolumes: true
    size: 10Gi
    storageClass: local-path
status:
  certificates: {}
  configMapResourceVersion: {}
  managedRolesStatus: {}
  secretsResourceVersion: {}
  switchReplicaClusterStatus: {}
  topology: {}
