apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: immich
  name: immich
  namespace: immich
spec:
  selector:
    matchLabels:
      app: immich
  strategy: {}
  template:
    metadata:
      labels:
        app: immich
    spec:
      containers:
      - env:
        - name: IMMICH_PORT
          value: "2283"
        - name: REDIS_PORT
          value: "6379"
        - name: DB_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              key: db_username
              name: immich
        - name: DB_HOSTNAME
          valueFrom:
            secretKeyRef:
              key: db_host
              name: immich
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: db_password
              name: immich
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              key: db_port
              name: immich
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: db_username
              name: immich
        image: ghcr.io/immich-app/immich-server:v2.7.5
        name: immich-server
        ports:
        - containerPort: 2283
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: upload
        - mountPath: /etc/localtime
          name: localtime
          readOnly: true
      volumes:
      - name: upload
        persistentVolumeClaim:
          claimName: immich-pvc
      - hostPath:
          path: /etc/localtime
          type: File
        name: localtime
status: {}
