apiVersion: v1
kind: Service
metadata:
  labels:
    app: immich
  name: immich
  namespace: immich
spec:
  ports:
  - port: 2283
    targetPort: 0
  selector:
    app: immich
status:
  loadBalancer: {}
