apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: linking
  name: linking
  namespace: linkding
spec:
  selector:
    matchLabels:
      app: linking
  strategy: {}
  template:
    metadata:
      labels:
        app: linking
    spec:
      containers:
      - image: sissbruecker/linkding:1.31.0
        name: linkding
        ports:
        - containerPort: 9090
        resources: {}
        volumeMounts:
        - mountPath: /etc/linkding/data
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: linking-pvc
status: {}
