apiVersion: v1
kind: Service
metadata:
  labels:
    app: linkding
  name: linkding
  namespace: linkding
spec:
  ports:
  - nodePort: 30010
    port: 9090
    targetPort: 0
  selector:
    app: linkding
  type: NodePort
status:
  loadBalancer: {}
