apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rustfs
  name: rustfs
  namespace: rustfs
spec:
  selector:
    matchLabels:
      app: rustfs
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rustfs
    spec:
      containers:
      - env:
        - name: RUSTFS_ADDRESS
          value: 0.0.0.0:9000
        - name: RUSTFS_CONSOLE_ADDRESS
          value: 0.0.0.0:9001
        - name: RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS
          value: '*'
        - name: RUSTFS_CONSOLE_ENABLE
          value: "true"
        - name: RUSTFS_OBS_LOGGER_LEVEL
          value: info
        - name: RUSTFS_VOLUMES
          value: /data/rustfs0
        - name: RUSTFS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: access-key
              name: rustfs-secret
        - name: RUSTFS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secret-key
              name: rustfs-secret
        image: rustfs/rustfs:1.0.0-beta.2
        name: rustfs
        ports:
        - containerPort: 9000
        - containerPort: 9001
        resources: {}
        volumeMounts:
        - mountPath: /data/rustfs0
          name: data0
        - mountPath: /logs
          name: logs
      volumes:
      - name: data0
        persistentVolumeClaim:
          claimName: rustfs-pvc
      - emptyDir: {}
        name: logs
status: {}
