apiVersion: v1
kind: Service
metadata:
  labels:
    app: rustfs
  name: rustfs
  namespace: rustfs
spec:
  ports:
  - name: console
    port: 9001
    targetPort: 0
  - name: server
    port: 9000
    targetPort: 0
  selector:
    app: rustfs
  type: NodePort
status:
  loadBalancer: {}
