apiVersion: v1
data:
  defaultPool: datapool
  iscsiPortal: 10.0.0.57:3260
  nfsServer: 10.0.0.57
  truenasInsecure: "true"
  truenasURL: wss://10.0.0.57/api/current
kind: ConfigMap
metadata:
  name: truenas-csi-config
  namespace: truenas-csi
