apiVersion: v1
data:
  defaultPool: datapool
  iscsiIQNBase: iqn.net.ts.orca-uaru.apex-truenas
  iscsiPortal: apex-truenas.orca-uaru.ts.net:3260
  nfsServer: apex-truenas.orca-uaru.ts.net
  truenasInsecure: "true"
  truenasURL: wss://apex-truenas.orca-uaru.ts.net/api/current
kind: ConfigMap
metadata:
  name: truenas-csi
  namespace: truenas-csi
