allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: truenas-iscsi
parameters:
  compression: LZ4
  iscsi.blocksize: "4096"
  iscsi.initiators: ALL
  iscsi.networks: 0.0.0.0/0
  protocol: iscsi
  volblocksize: 16K
provisioner: csi.truenas.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
