apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: truenas-csi
  namespace: truenas-csi
resources:
- config.yaml
- nfs-storage-class.yaml
- iscsi-storage-class.yaml
- namespace.yaml
- controller-deployment.yaml
- controller-service-account.yaml
- node-cluster-role.yaml
- node-binding.yaml
- CSIDriver.yaml
- controller-cluster-role.yaml
- controller-binding.yaml
- node-service-account.yaml
- node-deamonset.yaml
