# icon: si:immich # si for Simple icons https://simpleicons.org/
# icon: sh:immich # sh for selfh.st icons https://selfh.st/icons/
# icon: di:immich # di for Dashboard icons https://github.com/homarr-labs/dashboard-icons
# icon: mdi:camera # mdi for Material Design icons https://pictogrammers.com/library/mdi/
- name: Home
  # head-widgets:
  columns:
    - size: small
      widgets:
        - type: monitor
          cache: 1m
          title: Public Services
          sites:
            - title: Git platform (Gitea)
              icon: sh:gitea
              url: https://danicos.dev
            - title: Vaultwarden
              icon: sh:vaultwarden
              url: https://vault.danicos.me
              check-url: https://vault.danicos.me/alive
            - title: Immich
              icon: sh:immich
              url: https://photos.danicos.me
            - title: Linkding
              icon: sh:linkding
              url: https://link.danicos.me
            - title: Curious Ape
              icon: si:spidermonkey
              url: https://ape.danicos.me
        - type: monitor
          cache: 1m
          title: Private Services VPN
          sites:
            - title: Syncthing VPN
              icon: sh:syncthing
              url: http://apex-truenas.orca-uaru.ts.net:8384
            - title: Immich VPN
              icon: sh:immich
              url: http://hydra-0.orca-uaru.ts.net:30011
            - title: Linkding VPN
              icon: sh:linkding
              url: http://hydra-0.orca-uaru.ts.net:30010
            - title: TrueNAS VPN
              icon: sh:truenas-core
              url: http://apex-truenas.orca-uaru.ts.net

        - type: bookmarks
          groups:
            - color: 100 40 25
              # title: ""
              links:
                - title: X
                  icon: sh:x
                  url: https://x.com/Cosmedani05
                - title: Github
                  icon: sh:github
                  url: https://github.com/danielcosme
                - title: Tailscale Console
                  icon: sh:tailscale
                  url: https://login.tailscale.com/admin/machines
                - title: Syncthing Local
                  icon: sh:syncthing
                  url: http://localhost:8384
    - size: full
      widgets:
        - type: search
          search-engine: https://search.brave.com/search?q={QUERY}
          new-tab: true
          bangs:
            - title: YouTube
              shortcut: "!yt"
              url: https://www.youtube.com/results?search_query={QUERY}

        - type: videos
          title: Work Music
          channels:
            - UCD3mA_LbjO8V515Hw1jlYhg # Cigarette in Paris
            # - UC9fr5ejRTqZWIBn5CfqEKng # The Silent Gentleman
            - UC50fC49to1XtTsRamJbrnOQ # Halls of Moria
          # playlists:
          style: horizontal-cards

        - type: group
          widgets:
            - type: rss
              limit: 15
              title: Tech
              collapse-after: 5
              style: detailed-list
              cache: 12h
              feeds:
                - url: https://pmbanugo.me/rss.xml
                  title: Hight performance web
                - url: https://archlinux.org/feeds/news
                  title: Arch Linux (BTW)
                  # limit: 3
            - type: rss
              limit: 15
              title: Orthodoxy
              collapse-after: 5
              style: detailed-list
              cache: 12h
              feeds:
                - url: http://orthochristian.com/xml/rss.xml
                  title: Moscow Sretensky Monastery
                - url: https://www.oca.org/news/feed
                  title: OCA Feed
                  # limit: 3

    - size: small
      widgets:
        - type: clock
          hour-format: 24h
          timezones:
            - timezone: America/Vancouver
              label: Vancouver
            - timezone: America/Bogota
              label: Bogota
            - timezone: America/Montreal
              label: Montreal
            - timezone: UTC
              label: UTC
            - timezone: Europe/Madrid
              label: Madrid
            - timezone: Europe/Sofia
              label: Sofia (Bulgaria)

        - type: group
          widgets:
            - type: weather
              location: Montreal, Canada
              units: metric
              hour-format: 24h
              show-area-name: true
            - type: calendar
              first-day-of-week: monday

        - type: releases
          show-source-icon: true
          collapse-after: 10
          # limit: 50
          repositories:
            - immich-app/immich
            - go-gitea/gitea
            - sissbruecker/linkding
            - glanceapp/glance
            - jellyfin/jellyfin
            - fluxcd/flux2

- name: Entertainment
  columns:
    - size: small
      widgets:
        - type: twitch-channels
          channels:
            - theprimeagen
            - j_blow

    - size: full
      widgets:
        - type: group
          title: Videos
          widgets:
            - type: videos
              title: Homestead/Farm
              channels:
                - UCv2Li-PxOya3XCL-St_4DkA # Homesteady
                - UCkOTo20XS1LL95g2p6CcE3A # Few Acres Farm
                - UCBn3itOeDjCeuol70nQq1cg # Domaie Sauvage
              style: grid-cards
              collapse-after-rows: 2
              limit: 16

            - type: videos
              title: Computers
              style: grid-cards
              collapse-after-rows: 2
              limit: 16
              channels:
                - UCDAck-gFPTrgTx_qp59-bQA # Kubecraft
                - UCsnGwSIHyoYN0kiINAGUKxg # Wolfgang Channel

            - type: videos
              title: Fun
              channels:
                - UCtinbF-Q-fVthA0qrFQTgXQ # Casey Neistat
                - UCp00ppkfPFBUTiiNNd8kS9Q # Buttery Bros
                - UCixD9UbKvDxzGNiPC_fgHyA # Paolo From Tokio
              style: grid-cards
              collapse-after-rows: 2
              limit: 16

            - type: videos
              title: Machines
              channels:
                - UCBB0oz7Yo_35gnbPYGKGJTA # Diesel Creek
                - UCKqKiBDpq9j29bXbBx0cfOw # BuildWit
              style: grid-cards
              collapse-after-rows: 2
              limit: 16
        - type: group
          widgets:
            - type: reddit
              subreddit: technology
              show-thumbnails: true
            - type: reddit
              subreddit: selfhosted
              show-thumbnails: true

    - size: small
      widgets:
        - type: videos
          title: music
          style: vertical-list
          channels:
            - UCPVNT9hahuwpVwEpAgO0BtQ # Brutish Heavy Music
            - UCZD9nBgm7LhKZMOjq0-EOiA # DJ Nina Caballero

        - type: videos
          title: Monitor the situation
          style: vertical-list
          channels:
            - UCwrpo8z3IgJln2ZidqBUiMA # Cappy Army
