# icon: si:immich # si for Simple icons https://simpleicons.org/
# icon: sh:immich # sh for selfh.st icons https://selfh.st/icons/
# icon: di:immich # di for Dashboard icons https://github.com/homarr-labs/dashboard-icons
# icon: mdi:camera # mdi for Material Design icons https://pictogrammers.com/library/mdi/
- name: Home
  # head-widgets:
  columns:
    - size: small
      widgets:
        - type: bookmarks
          groups:
            - title: "Hosted in Homelab"
              description: "Hosted in my personal homlab"
              color: 200 50 50
              links:
                - title: Immich
                  icon: sh:immich
                  url: https://photos.danicos.me
                - title: Linkding
                  icon: sh:linkding
                  url: https://link.danicos.me
                - title: TrueNAS VPN
                  icon: sh:truenas-core
                  url: http://apex-truenas.orca-uaru.ts.net
            - title: "Hosted in Homelab VPN"
              description: "Hosted in my personal homlab, accesible only throught Private VPN"
              color: 200 40 40
              links:
                - title: Immich VPN
                  icon: sh:immich
                  url: http://hydra-0.orca-uaru.ts.net:30011
                - title: TrueNAS VPN
                  icon: sh:truenas-core
                  url: http://apex-truenas.orca-uaru.ts.net
            - title: "Hosted in the Cloud"
              description: "Hosted in my OVH Cloud VPS"
              color: 10 70 50
              links:
                - title: Curious Ape
                  icon: si:spidermonkey
                  url: https://ape.danicos.me
                - title: Personal Webpage
                  icon: mdi:web
                  url: https://danicos.me
                - title: Git platform (Gitea)
                  icon: sh:gitea
                  url: https://danicos.dev
            - title: "Public"
              color: 100 40 25
              links:
                - title: Github
                  icon: sh:github
                  url: https://github.com/danielcosme
                - title: X
                  icon: sh:x
                  url: https://x.com/Cosmedani05
    - size: full
      widgets:
        - type: videos
          title: Chill Music
          channels:
            - UCD3mA_LbjO8V515Hw1jlYhg # Cigarette in Paris
            - UC9fr5ejRTqZWIBn5CfqEKng # The Silent Gentleman
          # playlists:
          style: horizontal-cards

        - type: rss
          limit: 15
          collapse-after: 5
          style: detailed-list
          cache: 12h
          feeds:
            - url: https://selfh.st/rss/
              title: selfh.st
              # limit: 3

    - size: small
      widgets:
        - type: clock
          hour-format: 24h
          timezones:
            - timezone: America/Bogota
              label: Bogota
            - timezone: America/Vancouver
              label: Vancouver
            - timezone: America/Montreal
              label: Montreal
            - timezone: UTC
              label: UTC
            - timezone: Europe/Madrid
              label: Madrid
            - timezone: Europe/Sofia
              label: Sofia (Bulgaria)

        - type: calendar
          first-day-of-week: monday

        - type: weather
          location: Montreal, Canada
          units: metric # alternatively "imperial"
          hour-format: 24h # alternatively "24h"
          # Optionally hide the location from being displayed in the widget
          # hide-location: true

- name: Entertainment
  columns:
    - size: small
      widgets:
        - type: twitch-channels
          channels:
            - theprimeagen
            - j_blow

    - size: full
      widgets:
        - type: videos
          title: Homestead/Farm
          channels:
            - UCv2Li-PxOya3XCL-St_4DkA # Homesteady
            - UCkOTo20XS1LL95g2p6CcE3A # Few Acres Farm
            - UCBn3itOeDjCeuol70nQq1cg # Domaie Sauvage
          style: grid-cards
          collapse-after-rows: 1
          limit: 8

        - type: videos
          title: Hardware
          channels:
            - UCBB0oz7Yo_35gnbPYGKGJTA # Diesel Creek
            - UCKqKiBDpq9j29bXbBx0cfOw # BuildWit
          style: grid-cards
          collapse-after-rows: 1
          limit: 8

    - size: small
      widgets:
        - type: videos
          title: Other
          channels:
            - UCtinbF-Q-fVthA0qrFQTgXQ # Casey Neistat
            - UCp00ppkfPFBUTiiNNd8kS9Q # Buttery Bros
          style: vertical-list

- name: Info
  columns:
    - size: full
      widgets:
        - type: group
          widgets:
            - type: reddit
              subreddit: technology
              show-thumbnails: true
            - type: reddit
              subreddit: selfhosted
              show-thumbnails: true

    - size: small
      widgets:
        - type: markets
          markets:
            - symbol: SPY
              name: S&P 500
            - symbol: BTC-USD
              name: Bitcoin
            - symbol: NVDA
              name: NVIDIA
            - symbol: AAPL
              name: Apple
            - symbol: MSFT
              name: Microsoft
