apiVersion: v1
kind: Secret
metadata:
    name: immich
    namespace: immich
stringData:
    db_host: ENC[AES256_GCM,data:1tKO33/bK0xAmMLOcHF8IxO7ypILp8Dlwq1rUq4ilWGwGTv8+S9B+MJzGNFx3Q==,iv:l9LUG1K7JPjLAk8cDL9oZ+k/IugT9NiZcyxedUdJY2I=,tag:kwbDTFbOE6B+RneYEdxkmw==,type:str]
    db_name: ENC[AES256_GCM,data:XrYHdZpl,iv:S9Pso8AAz9mtdL1r9PhPogjfYcmTAjQF01lTFM4xcK8=,tag:7IYGnqlGy8Z0DP8JoS9R5w==,type:str]
    db_password: ENC[AES256_GCM,data:+oXLCZifcC03CRSGEyTs0qel9lkSFk6wauL7R7KesvKXTvXWnEFROA==,iv:6wOdb7/kfs/XnliALyAd6qhcRJcXLO+5juQ074LzBjs=,tag:TbPdvtSkFmso3pB8Gx3sXg==,type:str]
    db_port: ENC[AES256_GCM,data:nTfPZw==,iv:soROf6MLJJIBrCoh8cHPrBV0gDZLXIrihezH+402+EI=,tag:cxx0BeVgYz9tvWl5UFHfbw==,type:str]
    db_username: ENC[AES256_GCM,data:Pl/XFDWR,iv:l63f8mEau+0ZISRnpYg2+JQI55mAAQYAkuozRNpYgHo=,tag:/0lseB7D+9ndtIjXDa7Osg==,type:str]
sops:
    age:
        - recipient: age1lelpkv7u2xh5wezuwp09fmf9gsa8gp4rzy92jz0t203au82a7u5sutsjwa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUzJtNzFTUEFwSmVoTmpK
            Q1Q4K09OYTNSTnNpU3ZBeExiZ1ZLak9INlFJCmw3ZlhSOUZySU9mcDcxay9TL1Uw
            VisvSHpmNUR3aWJ3M2h6Y0phbCtEcWMKLS0tIFV4QXBYdmp6c3NZOWJFWUR4ZnNt
            S3dTcEdocXdyckdNV2NsWk50WVZ0b00KYcOUyMEzRCDJI91r3MzBUdIvJ4Qem2RO
            57U6pJvyPnAG1GY3/OcrPosheisoH4nNkPHxz3tkv7WWYNby3WetMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T17:37:12Z"
    mac: ENC[AES256_GCM,data:HnsWVad7+p3X3UUiOL3J71KkeEztMe2B9mLtWJbF7/r1x8TKXrnBjKqAmT/unr3LgYRuqNeMZ4mHwYk64P/T9PECTG/0dnDWpo+8sXxJL6/x0fR21gBwRUY3O8zy8VrEFCDeWy1qg0JrM1J3YyF6v2hoOiRsq0Qel2pql+Kdao4=,iv:SMZx9mCdRPVtMXDRztMRHG5oEfThV4UV70mctsoOS5c=,tag:lYIueK2PzLk7qTUqXdbyrA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
