apiVersion: v1
kind: Secret
metadata:
    name: immich
    namespace: cnpg-cluster
stringData:
    password: ENC[AES256_GCM,data:VkxA0bLvUCrZ0diI43jX3UH6ct1+WQPr6C5VWV3UB84yI9ykcpSI1w==,iv:NqMCPOZQK2mjlAZgo9YSg+Pd5ttg86XyDMWVtYdBI/w=,tag:harDScxSeaHuG5kQ6/zdAQ==,type:str]
    username: ENC[AES256_GCM,data:8SzMn5od,iv:Ms+En29rrpyYQFKx28RoS5QDouimOz/ouYaK+sOg1J4=,tag:clKYTXHC/BMJcaEbyCvw2Q==,type:str]
sops:
    age:
        - recipient: age1lelpkv7u2xh5wezuwp09fmf9gsa8gp4rzy92jz0t203au82a7u5sutsjwa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyeUxaVng1aUlDRVo1cEMz
            L0hweXdKaUdJUzZkVGdRaDhFdTJlaWJTOGk0Ci9DeEtxU1VnRDFNMDIzSmpUU0Fn
            RXVXQ2FVYmI0eVhUei8rNUV2TldTc00KLS0tIEdZVDJvY1pZYUZZNTdBYWZvQlBZ
            UUFzME1oZGZwVmNqRTE5dlY1aG81TjQKgKecbQunB5ggN663XBf74isxG3goUzQG
            DH0bfj95E0+xZ5STPrgWiu33NHJHATT/2W1A9OYWCn02gz6uJPhadw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T19:19:44Z"
    mac: ENC[AES256_GCM,data:2i2L+lRbzfQ+v252fB1oKgAmZr+cv0ozaYCz3Mhbq8vpSu5JteWbzM+abhBqP9cdvuiwJdEcXe2MOpxE/swlRBBHGGKDxLkIkpeCQWN98bghnyNZp5nhkDAnQzXnoV/XpwJRIQo3DM6v+2xWqxU1ira1asmhixFaMDfHQMI99bk=,iv:ihTqtmNk7nkgVGAkyhpcobuEEoZa++fzkBnqyFcEZyA=,tag:i0NP/vWVvl7uqjU1xUSAzg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
