apiVersion: v1
kind: Secret
metadata:
    name: immich
    namespace: immich
stringData:
    db_host: ENC[AES256_GCM,data:L0HLVyTp9Jp9DYghtHx1TB5NsEv+fBOnixqszjUvoF/uWXGb/xnZZGbxs3VOxQ==,iv:Nv9O1GqAIz0hQZ3rTE+lL2Rr6HSMu8MwHjtTpxzRWz4=,tag:Kg4oIa1PBfuscym7bZJ6XQ==,type:str]
    db_name: ENC[AES256_GCM,data:uXAmysLn,iv:WH0CSa/MgqAeoPiY+iiG20qsal+nqalRx5D21DF7fJ4=,tag:YH4Vy7NCIj20CBHJb4ELKw==,type:str]
    db_password: ENC[AES256_GCM,data:oP8mRF5f1YHdnLHDBGh58WUVoh3H7uBtarKnKgsnR35C4cQsHNud9g==,iv:MekInE4P4mNI3dbdkg8ltOQ7Cu6YGbrmbWL8zntpqjY=,tag:DKvZvg9pH/k0w7PIVRCZfw==,type:str]
    db_port: ENC[AES256_GCM,data:jYe7NQ==,iv:joakjKW/1F2ls/TqBcJHlOoVFJzocGieKurU0Pj8amg=,tag:Z6UoVh3FfIQ8U+WYO8D95w==,type:str]
    db_username: ENC[AES256_GCM,data:0ffOSkgC,iv:0XyDqJ89hm9Ej4QVg8qBOZzNlIKYX0fEceyY1IaTNzo=,tag:nl6jddgYlzwZ5P8oHqI57A==,type:str]
sops:
    age:
        - recipient: age1lelpkv7u2xh5wezuwp09fmf9gsa8gp4rzy92jz0t203au82a7u5sutsjwa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpaUh1YTVyM0g0Tmpsei9O
            ZUdrMkxLaU5ydy90aTJaZkNFbjBkaU02MFZvCmc3T05zS3EvTXVSZjFZMHBNMSts
            MXhYb21aY2ZSeFMvR1lUc1h1cnRhbjQKLS0tIDhWOWs1MC9nYm40RGNuOWJpTTVo
            MnpIdWdBSFAvM2ozZmlDc1lxR3JhTkEKsmQgoKGOslYoFq18RcTY13R0HJilfaD/
            aidHdBslKYU+QyRYAwNTr47cnuZ34OBYnWpfASyhTHexTkpH7Aqkjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T19:19:44Z"
    mac: ENC[AES256_GCM,data:VsetkkENkQ7JQsRX3ihytBUbXTOMwnlhsPs9FmQQTe6uO3lidYIOiqNsRObhg9Vs0To68aca4cZo132wFu/2nVMiK5+fItWfnJRKyf5TaN/1hILunAVdmZlD673XbogaazDHNGbX7qUMaUDB4O4vGtjbx+WXx2ez84vcP7Yswsw=,iv:MF7nccEGrxXcBPJmI2c4rtnKKBPlgQepT5HdntuGfaw=,tag:v9o78sJNOgYZsBJHBBqp6w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
