apiVersion: v1
kind: Secret
metadata:
    name: immich
    namespace: immich
stringData:
    db_host: ENC[AES256_GCM,data:vqjsHlBilWwkDWIiMgVzPixT3eYFahe5nAN13WgncuK1oJ6vb2fQ2dst5l5YEQ==,iv:DBGMlt1b89UrmmRpz9wGE/2aw/gb+BDxMtxpLLj5H/A=,tag:qwd+7Hzpkl5PuhekUO6eSw==,type:str]
    db_name: ENC[AES256_GCM,data:TfIDdII9,iv:VP2HpbJbuWYODEL2Q4AQGtFnDJldZ9c+jQ3CXbpjI1g=,tag:htY+NXoxa3rT7HfybCq/YA==,type:str]
    db_password: ENC[AES256_GCM,data:maypoiGDB5IKzViIZCwxzseLUNVslZl0PyGzDUMhj3EeFg/IZ0AMHQ==,iv:4GcRbBnZ3WeKCb/isA3/9HP+mZe6mMEvPiDRuMpaliM=,tag:NlNSwkIXW/eAk4wgotqozA==,type:str]
    db_port: ENC[AES256_GCM,data:lbYhpA==,iv:RI/rBTkife3FV/57Bl1wqh/m/6eDdnlTidKStMfptbo=,tag:Lpo/iSMWqxu0MssnBdkhSQ==,type:str]
    db_username: ENC[AES256_GCM,data:fM+tFW9c,iv:deAIYtSaRTlEZ8jMGe0mOOTf3kX9K+65PNe1cCbjUPI=,tag:ukbExsLJ/iF8lD7PVGMk5w==,type:str]
sops:
    age:
        - recipient: age1lelpkv7u2xh5wezuwp09fmf9gsa8gp4rzy92jz0t203au82a7u5sutsjwa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBya2d0UzNyTzJqOEUvV29i
            S2NXSW5EclRKWXdNR0psMUtLMTE2VnpmK3d3CnBIQlRoakxDYkxhaDhQNEdsL3Rw
            ckZEcnpna1JvWVVBOUJFNmNEYno0eFkKLS0tIGt6S1JqZldGT2JySjJYaWJOazEw
            cElEYU1ZczFzSVZuYld2OHg3ZTlUR1UKXLyw99wih83XjAC8DjyYUSlNV6xm/eZO
            MVgwjygjrzkQUEzlg6QZkNc+9l5Cxoga/dEHKUusVhrXetatXQatAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T16:33:06Z"
    mac: ENC[AES256_GCM,data:LeuhcXFhl42bwIlbj+tCFLT0befXQM7jKv3mUo5aR2FNBbPL1k86P92WH56sBqfHIbS9JYpF/Tsb/M5HkKyEMenJ6SZO7HIGrBml+2nBYoukLt2CQo1FmGk8q5boZEhqzAMTHC3tgUjRlbHd/wwfcsOvCeGvrb4VYzUFYT7xAYI=,iv:zi8SzzrhrcsXV8z6lg78LGI513MpBmeJARnKmxA+vgY=,tag:Fnz+xLsaeTNmyr7cwiflKg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
