apiVersion: v1
kind: Secret
metadata:
    name: immich
    namespace: cnpg-cluster
stringData:
    db_password: ENC[AES256_GCM,data:ExUIjDrV6bpFb49SaWV8SDwWyBOF58rb1xAtOvu8Jqz09VsGKSEupQ==,iv:fQ9rfAcerYzaFMdbrWsZ/YR/cGPhHrExtc+fVoW/2dk=,tag:VSJC2Y7xIzY8s4o4sOvfVg==,type:str]
    db_username: ENC[AES256_GCM,data:h4JMTcRY,iv:QnfMeP002cRvldSfSZfVd5LHVrAlEUOy9EJhTr0ZC/8=,tag:KkL5EogpD3zNR1Nq6gVJbQ==,type:str]
sops:
    age:
        - recipient: age1lelpkv7u2xh5wezuwp09fmf9gsa8gp4rzy92jz0t203au82a7u5sutsjwa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFWTBvZVpuRzhuOFFuVmtY
            QzZWcmVXRFIyZ1VJL0dneDNOTnptUzVHMmpjCmQvZkJHM2xlQVVCVDloVU5hUFFy
            MExnbktKajErNWtjbDZ6THI2ZDVBNTgKLS0tIGdSaUFaNzRRZWd5Z1FockVJanlm
            eFJac3R0Mms5eXk2M2pNOG9SNzBPNFEKmNUhnZHDV9HJ0WlZfnnsSjq9Q7Fe89lD
            79xHtPRVZ2EdfETDGM6KvQQV1nCDZwgEl1EgajUcVP9dSuIpoH7HmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T22:22:16Z"
    mac: ENC[AES256_GCM,data:3exs28tq6RKN3WGFGTzAJXLpTzAsUJEkHRdM3YLD0H3j0b9tDYPOcL/7N7OHA9DKUm1nbQrpNiDVU2w+FemSGOgxqSiNIkjhyilIykn/ZE+YlISG7zWoj60OgylKdbsM/dC9bBvlu/VhoDxdCg/BKFBk0h403NOs8gdQOMVp3H0=,iv:ANgAYhusC0J0SlqShRk0AHFktNsjWrT36cQww85ZkG8=,tag:+Gnx3Mv9bCToWVEiNb7Fag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
