apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
    name: secrets
resources:
    - linking.yaml
    - truenas-csi.yaml
    - immich-db.yaml
    - immich-secret.yaml
sops:
    age:
        - recipient: age1lelpkv7u2xh5wezuwp09fmf9gsa8gp4rzy92jz0t203au82a7u5sutsjwa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQT1JqVktZQjBFU1JPbVV6
            TjBlU2oyaXBOcFlwSGlTTzEwWGlpMXhzTXpzCkM4djNnNThhUTZoQmxXM3dBbEFZ
            Nmdob3IzV1ZSazBaVWp6eWJnbnVVeVkKLS0tIElQZzJZR1hmNFVGM1FhazdiejNX
            Z05ZMm12L3R4VHhrVFBJZ2pJZ2d6b0EKPYPaGIgyi3NEnhMQC8b9LmPHEc2ntkqE
            hlSdNzu215XEFEdCfOu5r0M99EcB+MtNxjwNOaw3XznaaDh48bvICA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T18:43:05Z"
    mac: ENC[AES256_GCM,data:yHWDQ9FJiEOh3UjicbcF+fRxGZDA6rGXyIdH/Omw4CoiZ+S16ySFt/310AB75XfKrFXvimqtWOfQ2N7/1EGWU0fWCMczUGyPB2C+0O0aEsTpJ9KsHgbPy2StfXV0xaH3JEdg5IjrSvNnd3pPy46Zi5jCI38eet7wg5h+dEDN0NY=,iv:n9Ghm44mb6dqCF43ghKb7q3lDeeAumG5W8yVhQqkxVs=,tag:dA4MyLk/VgYzzU7YaFCncw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
