apiVersion: v1
kind: Secret
metadata:
    name: linkding
    namespace: linkding
stringData:
    supe_user_name: ENC[AES256_GCM,data:kDeIwS4IcrXPPO6ZxkhPXf4=,iv:7IEB0WjRpNmQz7Vfwa6qZNWomACoXQwH3Y6SfIPdgd8=,tag:JGFwt7nfhR8HqpUlUb+Tqw==,type:str]
    supe_user_password: ENC[AES256_GCM,data:+2N0zdCiCSiYguhAmggMHkPWjBDLZ1+oxh/F4W4sBfTk54K9z3CNBU9nUvw=,iv:JYUzvHpNM0ECKf9JDQfwcH0DnZDBo7YNgaPHJzslftk=,tag:r3PSQofyxNoLweZcz8OokA==,type:str]
sops:
    age:
        - recipient: age1lelpkv7u2xh5wezuwp09fmf9gsa8gp4rzy92jz0t203au82a7u5sutsjwa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuWWpDa1RCM20zblFiZEZG
            MkcxVGlrN0thNURDaHIySU9xbG1CQ1FPNHowClBsUmpuVHVqaGNFWWd0VEVjYXFs
            Yk5ZZ1BJVUQzMkFCbmRraUlSYkZ5SlEKLS0tIFBDZXlERFp2alJJelhrOER0S3pF
            Vms3MW1sQm8yMk14OTk2THp0ZHpkc2MKiXJn3ZOUfh2W7UoYB2NHZ0Es9l7WJhaJ
            9cbedKWQt53ySKYfWKSC742wJ+mQZTIyD4zxh4RmT7GL166N6yJSoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T22:17:42Z"
    mac: ENC[AES256_GCM,data:38wsQscf4Ngz5RtBHvWK+aq6Qq2oKK5Y338akWTQW9CbObh+ltikJkx9xKYSwmSrLf9D9Cal5NCejqHCU2S32QbPR+Jf7E1V9KYScTuiHxLLiepYUYhyD+K8S8B9M0mupGuEsnfmW1gOV6VQepqhDmyw2D6UhoTz8MFSrrTnA4I=,iv:45wGTvc9Vx48xhl+bkpvBhlGNPSUJh9ZPaHH2Sov0NI=,tag:afIY1nQl2YS2J/kx/ZRWQw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
