apiVersion: v1
kind: Secret
metadata:
    name: linking
    namespace: linking
stringData:
    supe_user_name: ENC[AES256_GCM,data:C5CJpeN9QQROt7QC+WO/eOc=,iv:UC3fozXsI5MQbp3K2YTFDwIcdSJj1YA+CfwuRF8+uyE=,tag:WUEvyT6td9IJZIqvIOx/Ug==,type:str]
    supe_user_password: ENC[AES256_GCM,data:5ieWvqHulWrgK0kHUD+P/6FttjYl1wqDrOQe8zXnEDuhxaTrzOedkTkvnvo=,iv:8n2fW9vTcxgE65UBpSGDbLm8TkHM4AtvCl1wyKnRjmY=,tag:GpGJuLpQEknScDG0UiAtGg==,type:str]
sops:
    age:
        - recipient: age1lelpkv7u2xh5wezuwp09fmf9gsa8gp4rzy92jz0t203au82a7u5sutsjwa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4K2NUTUVSam9ZTitYbUhy
            dG5GOSt6ZGlvMEFwQUViTUE2c05xT0JSdmxzCjhrS055RWM4UFNnb0hlSWxmYzNV
            K2dSWXBMcURHdjJ4T1dJVm1LUDUzcVEKLS0tIHlqcHpDeEh1OWltRVFJMDFuWllC
            MlNDdWFKeHJHL2pCTEJUcUhDdHg3S2sKFUfecGAmRjUXg1MVtey+zeqCLuSBQgy4
            nGC+zojDH6+LX3aS4um5xpil+ZtylTHIq97rjZG/7UFQoNhgxoX74g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T22:25:01Z"
    mac: ENC[AES256_GCM,data:WLTtDu9cRlcb4nBFluuVMpFHxz6UB07H0ntNukq9p/XJnGFQSBKISP/nQ4dcqK1zzMhmhlRcFeZAXXvmJaEJuAaZRV7n1dkgHZtTC2ZXTuGIvB2NrC0phNcw17QMvLEvxUVMmjLkIk+syGJuNhvypp7COcKRnA350MsMcJ2tbUI=,iv:ysEejhg7H/J5TXEMmM8gI81tY7IcNsHkZW852idSaCk=,tag:jt8l4NsyaIC3oX67rVe0+g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
