apiVersion: v1
kind: Secret
metadata:
    name: linking
    namespace: linkding
stringData:
    supe_user_name: ENC[AES256_GCM,data:vhWZevOo3I38ovyEcjMAWqI=,iv:tJBB8q/j++EeBh9xkbV8b0Z4Cjv+FfAhCMvcvuCNHiU=,tag:TaNZD57gc4YPC0F9XMG9Zw==,type:str]
    supe_user_password: ENC[AES256_GCM,data:3AmIPdvgT9Sm3NnBZOrNwavqufZ8qMDF2mmArGRZu0E7BHh+ACdA4va1LWU=,iv:BneAVoeEkRp1JxKqMuwqld8fq5BEWCCtPDGUId69egE=,tag:swsQQhBmahluZq104KPs7w==,type:str]
sops:
    age:
        - recipient: age1lelpkv7u2xh5wezuwp09fmf9gsa8gp4rzy92jz0t203au82a7u5sutsjwa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiK21KOHlwemhCVDVVRnVh
            YTNJZWFsUGRsZ2RrQmRTSGdMbmZMQlRYMlRNCnFMR2VZd2dCY0p4SjR0NUFlT3ZM
            VW5oa3Q5K3EyOW9KMWd5TlZVWnVBd28KLS0tIGxOUDBQMllaY0pxRWFhZHRiZ292
            d014VjIveFprV1VzSWJZU0FPeGNTU2MKsmNy2B8d+RnaOAQptvinUGSly/tDhfne
            oaymAmk4Ekn455auBK/mAez641hJleYmUYpSfNQP6JyEYgrQBHfbfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T18:44:47Z"
    mac: ENC[AES256_GCM,data:6tM/koVtZU1FWhNQ7w9Rbksu/tbjEEErgtxtJPjPjMtE9bfdtSd+vpojS2haZ7UKmfEwT/jUN/nSdtQ9ktdKpVqDx0S9SuQ6fhToIgdrKQyHO/CGBzLSrWl32OhB9gdLajGlpINi2MTjQ1EjudgDgovhg5TBBEwFU3AeFuwtNNo=,iv:v7XQiE5JV9raVCvfGf7x+BomPHAKgHxwU/uldX7Q5+M=,tag:B/mwaoNfWjLQZMRzxnIgMw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
