apiVersion: v1
kind: Secret
metadata:
    name: linkding
    namespace: linkding
stringData:
    supe_user_name: ENC[AES256_GCM,data:Fzvet2NQ2suwjl1sOmURp6A=,iv:osYJ+RylMvMWbn9oe3F690GfZ57FGTy72bKXmcK/wfo=,tag:exwKVf30KaRzO2GukYRlqg==,type:str]
    supe_user_password: ENC[AES256_GCM,data:Oys6Dves2m2OwvddpdJLdrY6XU1v3ws6fPMokkk1YQh05WtcAlznutgoEsM=,iv:Sfuhzp6NEry+iw90xqMzfC4vRNZAZENGTI5CVQo63DY=,tag:pSwgWBnlJi98UT1/mhZROg==,type:str]
sops:
    age:
        - recipient: age1lelpkv7u2xh5wezuwp09fmf9gsa8gp4rzy92jz0t203au82a7u5sutsjwa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1S1lZZmYvbWc0ZHZCUzNp
            Vythenp4UkJHbG5nT0dSY0Zid2FUT0hBN0RRCnZYRDdDdEZ1L040MERMZGpYVU91
            U1hwZW8ybmU4WGVOZjJrZ1o1T2dKV3MKLS0tIEFhV29nekhEUTcwU1NLeVZNRW42
            a09pOTR1MXl3TzRkcVB1TnFaM05XakEK8Dqp8O6oaHQEi9yKcXkM5NhpPwYhfhxi
            E/mfxXSNT+2aHi5GMvrSS734ET6KuC6te2Fr/Ik5iySIjPZVITxWHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T13:03:24Z"
    mac: ENC[AES256_GCM,data:/Irwkg+Nq6OzThm0kbhxa3Y5y8j28DRNlO039IpiSRz0YhMicHzeJ9dQIv/9POaKkjZGkPB6o1Puwhr6MuugocEouLrAlBxd0msNFHSQrNPEwVhOQv6gKFElbKrvHSsli6iNtTouTdLEp3V7PHumDn3OZAoMq9DGl/G64nJ0fh8=,iv:qXlXLlFwOa8Bk/iFHB6SbRf2UJgVPX6v2o8pXKgXfrE=,tag:m3De/z3Y/TJDHgxoHKIMqw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
