apiVersion: v1
kind: Secret
metadata:
    name: linking
    namespace: linkding
stringData:
    supe_user_name: ENC[AES256_GCM,data:ZMkfWVRHm6uZR9PqIJ5EU5U=,iv:iWi5ugiJ8kfQvWRbyklXZlSQIsK/8jwdDN56+hsnw1E=,tag:m/vGA/VCO8DrcHBNg7nN8Q==,type:str]
    supe_user_password: ENC[AES256_GCM,data:is9qoeVlErxBityCY9WIPxUmvTvDbRTVFJgHkR6u3PR8NG3G0N2jUx/3pfA=,iv:wZb+o+KgiklC9udVbX9VeWWDDJG8Oqu7CKNevwnHXyc=,tag:6e9pcKHuULgwrr1EwyKFRg==,type:str]
sops:
    age:
        - recipient: age1lelpkv7u2xh5wezuwp09fmf9gsa8gp4rzy92jz0t203au82a7u5sutsjwa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWlpQbUYzdmUxWXVPaC9q
            MmNXTVdaT3pNMkNYc2xxUzJxeVZ5eEVlM1hjCjdsdXc2NzNGbG5XUy9aOW85OXE1
            SkdHak5VQThBYlJQVjdhMHJlU20rUzgKLS0tIE1ZeHpsLzRoOXFuK0JmQXZUZGxC
            OStxN1l1dFF1YUxuRmhYR2JtS2x6dGcKRrkOIvaZqLIvQU3yaRgnbytrlCy9vCkz
            k6x2lHkmUD0W0vZu4gAvMsvdyjU1mGdzDVOqaw6suxGBg+ak1ke1CA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T21:24:52Z"
    mac: ENC[AES256_GCM,data:tN8v+m81rGKjnWA3kIFsnZq9nPi+kT/RgjWaLDd/PLq418kZPkRAUJJX/JaBbozjVS/EYjG8YYz+jyCrI60nrLxH6yJhiRIeIGOYWVUAbHOzEpbVXS2aFZdfSHtG848CcCrV4wzqJ3xgbbgu/I0gEAnOzQiP6DFOrHa8DgonXwo=,iv:nvpz5SOe9j+44pZifAEOp6aEd14WLyXeZc4XoK4IKHI=,tag:k95ZJRwSNj2peNSnpfzXrg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
