apiVersion: v1
kind: Secret
metadata:
    name: rustfs-secret
    namespace: rustfs
stringData:
    access-key: ENC[AES256_GCM,data:kQWU/G+F28Rs2CU=,iv:FBYl9HCfWZ6afaebY1kZAKDEAM+D4KiVZqjVmxyftGo=,tag:h2318IhSJzz30GZCnd7Bdw==,type:str]
    secret-key: ENC[AES256_GCM,data:8lS1x2ljGup1I1Rnu0R8UbsPiBD1cLz9mjknXUk6VilOn9XLpYstwt7Rg3/EuIMeIUWjn9k=,iv:nnRuhvYvSn5HVRychFthcsfK7Z/4wAyEZKcu8h3EWU4=,tag:6U20loIkvrKzXAactsAf5Q==,type:str]
sops:
    age:
        - recipient: age1lelpkv7u2xh5wezuwp09fmf9gsa8gp4rzy92jz0t203au82a7u5sutsjwa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvbU55OElGRnVyb25sUEVS
            MFViNktXMjJkMzZ6RGRSVks1aVRUeVRKK1FJCnVIdmFTeUEvL05pS1NtYWVrYldS
            SURjYTEzc2p6TnFFaEVRSWhvUDJHTkEKLS0tIERyd25OWmtwanVsWUxQVzFaRncv
            b3cybUJ5NmRnbTJWNTQrMmpZdnNEd2cKM/zod9g0NbZEScbD2hYZ1HOezL5Z5aya
            pS1DVZpVFL+6Os9mTbehIZfgTlS3XKWHWy0Vtk0cR4JrWJqkbxXo7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T21:24:52Z"
    mac: ENC[AES256_GCM,data:YETMO7UbV7h1HXUjbE8Mz8dPLzroERHv0zq3RThFZB2xySOuyVT+3K4UiJoCC3wMpWNg/peflkashCpZewaPRSEUBgrMxz1iKVC+S8gHaF4nEfKcD5dQh9IXtQPikIL6ZS/fPIOqVb5KXPHqFMuEDe0IJ5ErNwhjDgarL6P3Xgk=,iv:Pus57vT0FKBOUYuhCq8bwipwhJtZMxxfdNxPu+/ELmo=,tag:YkhSy5dXU1RHUMVFVJCNRA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
