apiVersion: v1
kind: Secret
metadata:
    name: truenas-csi-api-credentials
    namespace: truenas-csi
stringData:
    api-key: ENC[AES256_GCM,data:+JGzrilxagXUW+MstFXYwCApP8xxRjghuFECjszJA/e+DLIH5gaqdNNZN/rsZj1PeZJy4Z66GNm8okDnuciW33k5,iv:d36D3tdDhvoUCGzPUnD3Q7owkfTTdh9ZhU5g8d3tZ/Q=,tag:et6a6dRmOUT8lzXcVXzbwQ==,type:str]
sops:
    age:
        - recipient: age1lelpkv7u2xh5wezuwp09fmf9gsa8gp4rzy92jz0t203au82a7u5sutsjwa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByem9YaTBWWXpDcmhvV3BR
            SzMrWEF4ZkJmQUpsa3pLRlFKOXE0Q3Y1ZVEwCjJseVErRGI2ejdyMjZOZ0c3RmhD
            eVdUSDRUVkJVelJ3eHltcm9XdW9UTDAKLS0tIGJ2RkliUmZVMlhocEZ4aWlXSVFN
            MkNXbTdWTGMwUHdiN2dpQmJCQ1JIcmcK2c1eZtC9wKaeGs82YudNcKt5cyToC8uo
            cLinWd2v1h3QGHMI4P1KfqS6xgMhgZQeR4ozEuV0CZGjAgYJaKPsAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T18:43:05Z"
    mac: ENC[AES256_GCM,data:Eq4p2ny8p3fVfEoGnQa9/lZ5DYxiWOUe0BjF0FUyE36RVKG6ci9AHiVAcO55STiOV5rQmZKdSUi4XH3WliFr8Myi4459OUENKuAn2qkShQWXelvRW89IAF35ItBZ+urP4H/xq49v21Mw4xUnagMktz00xdeCiMOjvlhN5g2x6Nw=,iv:CPEpYu0f3mISKayq54oCYJS0LXpT8ZFszGPdjrL8kWM=,tag:MKpVkrFbWlP5RvBwiLA2iQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
