apiVersion: v1
kind: Secret
metadata:
    name: truenas-api-credentials
    namespace: truenas-csi
stringData:
    api-key: ENC[AES256_GCM,data:qjm3UeKS2MPTNCg4GhcR+vq74Hza8P10FFDrAbmzoPE3PS8VyIxucFSIvIk7IkDtG6YHlW91KXPqExIzquNM2fFd,iv:JyoL1jOFNH1NotpHrqxVq4+HREeaYgE3bkeEO5uTs7c=,tag:5llAWqj7/Ml5/sSqplbl6g==,type:str]
sops:
    age:
        - recipient: age1lelpkv7u2xh5wezuwp09fmf9gsa8gp4rzy92jz0t203au82a7u5sutsjwa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcC9sZ1FhbjU1Y2U2Z2hz
            WkEzZFZiNk56My9tRDJXTnhLaXJ1V3lBeEVnCndUcjFvTlh6aFFWbnM1N3BsaTgv
            WHkxeDVZdEh5Uno2bkF5QnlSeEl3NGMKLS0tIEJnRDFRZmJpaGhhcFIvVVNyRU80
            M3FiRWFpa29hdGlTMG5aa0lNajRHSHcKFzeMQ82WD85tmnBmUy16BzCmqIEcad7B
            atNXtrNCW8RFiFiu+zDUd628DiQIsvPXCx5ugCoiJlc3jxSNMOHtIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T19:19:44Z"
    mac: ENC[AES256_GCM,data:wwI5KlD+917zgLKqSDTlLnd90DQo7mNcK0oHnd+8ou2KI3UM4xg4zVKZSitOelgmbP4G12K3uBHpya60GP30mFVetqgghs/gSoUakyUG3C8LJuOUS8iYemESx5J/02hfDRFVLripiumtQGIGMahVbskLt2F5vo65djdu5JJqFMo=,iv:0J+AUZ5GfNc3E4NtSXw4DZrWt6fNhj40Vl4+pwlm45Q=,tag:WVuXRkO583xQ7j06m2FBeQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
