apiVersion: v1
kind: Secret
metadata:
    name: truenas-csi-api-credentials
    namespace: truenas-csi
stringData:
    api-key: ENC[AES256_GCM,data:CitMTwW7Fnkz39PthZ23Zo+BZBtbJQzVtjFgR0tPmZiSZ9YxXySaf3PH+N7RoA5X38bd+Lrg9/YMEvOVsagQAkXW,iv:lqfA/PnoPVLYW9CXudXfMSsCDPxf0Mn8iLr2mozbSbg=,tag:+5eOFLr6tt4Oh/3J2CFYQA==,type:str]
sops:
    age:
        - recipient: age1lelpkv7u2xh5wezuwp09fmf9gsa8gp4rzy92jz0t203au82a7u5sutsjwa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYQ202RU1GVzdqQitVZEti
            U2FIVjNKMzNYMHU1Nmg1MmtJV2xvaUF6VEd3CmZUQWtKRlE2MVFsSGoycE9yL3Vp
            ZzVpOERFekZLVTJFNk1PMHhIVHZ5NDQKLS0tIERNRWw3a29FUmxoSWpvU3RlbXYy
            TjJrUVJUZkZFQkFFbi90ckJpRWVJaG8KYBoxszg7Ah91yVLs/8T5poo6S5TC6sRr
            tyLqwwA3SUIrdPLI/bYON74ZyB95khHIN0em1OMtMYY+Ok4gJuH1Ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T17:37:12Z"
    mac: ENC[AES256_GCM,data:aMiws/+k8OaL9qdDrXBwq7aAqnUZMtDCFM9WG4kt0dMT4MJf5mxqaoz2RDupAWaWjQ3ccxW/WoGFazRmuIdPnoeyVsTRfwLMa17+HIvOyAZAajqKnUqIGazYjgcQiw8S4D+B9oa5Jl+PFu6bIHiWJLaHw9m5WrU55olJzRpOnNs=,iv:nh3crjtwYICi6IUiX1gZD5WOc3A8KkuCAVbBnv0LsEs=,tag:J1CneXNbRlSqf0PY/QEG6w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
